### ISSUE TITLE
Link to Assets in Files Anywhere

### ISSUE THREAD

**Issue by AngieMurphy** [HealthStart-Monstralia/Monstralia#28]
NEW LINK - https://personal.filesanywhere.com/fs/v.aspx?v=8d6c6a885f6772b8a6af

**Comment by jacob-bobb** [comment]
Updated 3/22/16

**Comment by JFollin** [comment]
NEW LINK - https://personal.filesanywhere.com/fs/v.aspx?v=8d6d65885f6471ada5aa
